ENVIRONMENT:
  MAX_EPISODE_STEPS: 1001
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 10000
SIMULATOR:
  TURN_ANGLE: 30
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 360
    HFOV: 70
    POSITION: [0, 0.88, 0]
    NOISE_MODEL: "GaussianNoiseModel"
    NOISE_MODEL_KWARGS:
      intensity_constant: 0.1
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 360
    HFOV: 70
    MIN_DEPTH: 0.1
    MAX_DEPTH: 10.0
    POSITION: [0, 0.88, 0]
    NOISE_MODEL: "RedwoodDepthNoiseModel"
  ACTION_SPACE_CONFIG: "pyrobotnoisy"
  NOISE_MODEL:
    ROBOT: 'LoCoBot'
    CONTROLLER: 'Proportional'
    NOISE_MULTIPLIER: 0.5
TASK:
  TYPE: Exp-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SENSORS: ['GT_POSE_SENSOR', 'GT_EGO_MAP_ANTICIPATED', 'COLLISION_SENSOR']
  GT_EGO_MAP_ANTICIPATED:
    MAP_SIZE: 101
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [0.2, 1.5]
    MAX_SENSOR_RANGE: 5.05
    NUM_TOPDOWN_MAP_SAMPLE_POINTS: 20000
    GT_TYPE: 'wall_occupancy'
    ALL_MAPS_INFO_PATH: 'data/datasets/exploration/gibson/v2/train_large/occant_gt_maps/all_maps_info.json'
  MEASUREMENTS: []
DATASET:
  TYPE: Exploration-v1
  SPLIT: train_large
  DATA_PATH: data/datasets/exploration/gibson/v2/{split}/{split}.json.gz
