BASE_TASK_CONFIG_PATH: "configs/exploration/gibson_train.yaml"
TRAINER_NAME: "occant_exp"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_ID: 1
SIMULATOR_GPU_IDS: [2,3,4,5,6,7]
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
EVAL_CKPT_PATH_DIR: "data/new_checkpoints"
NUM_PROCESSES: 36
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_EPISODES: 10000
T_EXP: 1000

RL:
  PPO:
    # ppo params
    ppo_epoch: 4
    num_mini_batch: 4
  ANS:
    image_scale_hw: [128, 128]
    MAPPER:
      map_size: 101
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      ignore_pose_estimator: False
      map_batch_size: 420
      use_data_parallel: True
      replay_size: 100000
      gpu_ids: [1,2,3,4,5,6,7]
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_ground_truth'
